(() => {
  const steps = [
    { icon:'↗',tag:'NEW INQUIRY',symbol:'✳',title:'A new opportunity just came in.',description:'Sarah requested AC service. Her information is captured and ready for immediate contact.',footer:'Lead safely entered the pipeline',mini:'System listening for new leads',detail:'Everything connected. Nothing to manually transfer.' },
    { icon:'☎',tag:'FIRST CONTACT',symbol:'☎',title:'Your system responds right away.',description:'An immediate outreach attempt starts the conversation while Sarah is still looking for help.',footer:'Response action initiated',mini:'Lead contact in motion',detail:'Faster action when timing matters most.' },
    { icon:'↗',tag:'FOLLOW-UP ACTIVE',symbol:'↗',title:'No reply? The conversation continues.',description:'If Sarah doesn’t respond, a helpful follow-up sequence keeps the opportunity from disappearing.',footer:'Recovery sequence activated',mini:'Follow-up working in the background',detail:'Every message is part of a clear journey.' },
    { icon:'✓',tag:'JOB BOOKED',symbol:'✓',title:'The inquiry becomes a booked job.',description:'Sarah is scheduled for service and the opportunity moves into the booked stage of the pipeline.',footer:'Booking stage updated',mini:'Next step clearly tracked',detail:'Your team can see what’s ready to service.' },
    { icon:'★',tag:'REPUTATION GROWTH',symbol:'★',title:'The relationship keeps growing.',description:'Once the work is completed, a review request can help turn a happy customer into stronger local proof.',footer:'Review request ready after service',mini:'The customer journey comes full circle',detail:'Great experiences can build future demand.' }
  ];
  let current=0;
  const els={next:document.getElementById('demo-next'),reset:document.getElementById('demo-reset'),icon:document.getElementById('activity-icon'),tag:document.getElementById('activity-tag'),symbol:document.getElementById('visual-symbol'),title:document.getElementById('activity-title'),description:document.getElementById('activity-description'),footer:document.getElementById('activity-footer'),mini:document.getElementById('mini-title'),detail:document.getElementById('mini-description'),progress:document.getElementById('progress-fill'),counter:document.getElementById('step-counter'),label:document.getElementById('progress-label')};
  function render(){const d=steps[current];els.icon.textContent=d.icon;els.tag.textContent=d.tag;els.symbol.textContent=d.symbol;els.title.textContent=d.title;els.description.textContent=d.description;els.footer.textContent=d.footer;els.mini.textContent=d.mini;els.detail.textContent=d.detail;els.progress.style.width=(((current+1)/steps.length)*100)+'%';els.counter.textContent=String(current+1).padStart(2,'0')+' / 05';els.label.textContent='Step '+(current+1)+' of 5';els.next.innerHTML=current===4?'Replay demo <span aria-hidden="true">↺</span>':'Next step <span aria-hidden="true">→</span>';document.querySelectorAll('.journey-step').forEach((item,i)=>{item.classList.toggle('active',i===current);item.classList.toggle('completed',i<current);let state=item.querySelector('.step-state');state.textContent=i<current?'✓':''})}
  els.next.addEventListener('click',()=>{current=current===steps.length-1?0:current+1;render()});els.reset.addEventListener('click',()=>{current=0;render()});document.querySelectorAll('.journey-step').forEach((item,i)=>{item.addEventListener('click',()=>{current=i;render()});item.style.cursor='pointer';item.setAttribute('role','button');item.tabIndex=0;item.setAttribute('aria-label','Preview step '+(i+1));item.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();current=i;render()}})});render();
  const menu=document.getElementById('menu-toggle'),mobile=document.getElementById('mobile-menu');function closeMenu(){mobile.hidden=true;menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','Open navigation')}menu.addEventListener('click',()=>{mobile.hidden=!mobile.hidden;menu.setAttribute('aria-expanded',String(!mobile.hidden));menu.setAttribute('aria-label',mobile.hidden?'Open navigation':'Close navigation')});mobile.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));document.getElementById('year').textContent=String(new Date().getFullYear());
  const observer=('IntersectionObserver'in window)?new IntersectionObserver((entries)=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.09}):null;document.querySelectorAll('.problem-card,.section-head,.center-head,.process-item,.pillars-layout,.cta-card').forEach(el=>{if(observer){el.classList.add('reveal');observer.observe(el)}});
  const form=document.getElementById('lead-form'),button=document.getElementById('lead-submit'),message=document.getElementById('form-message');
  function fallbackMailto(payload){const subject=encodeURIComponent('Ignite Co. website inquiry: '+payload.company);const body=encodeURIComponent('Hi Ignite Co.,\n\nI would like to discuss a growth system for my company.\n\nName: '+payload.name+'\nCompany: '+payload.company+'\nEmail: '+payload.email+'\nPhone: '+payload.phone+'\nIndustry: '+payload.industry+'\n');window.location.href='mailto:asher.igniteco@gmail.com?subject='+subject+'&body='+body}
  form.addEventListener('submit',async e=>{e.preventDefault();message.textContent='';message.classList.remove('error');const fd=new FormData(form);const data={name:String(fd.get('name')||'').trim(),company:String(fd.get('company')||'').trim(),email:String(fd.get('email')||'').trim(),phone:String(fd.get('phone')||'').trim(),industry:String(fd.get('industry')||'').trim(),website:String(fd.get('website')||'')};if(!data.name||!data.company||!data.email||!data.phone||!data.industry||!/^\S+@\S+\.\S+$/.test(data.email)){message.textContent='Please complete all fields with a valid email.';message.classList.add('error');return}button.disabled=true;button.textContent='Sending your request…';try{const response=await fetch('/api/lead',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(data)});let result={};try{result=await response.json()}catch{}if(response.ok&&result.ok){form.reset();message.textContent='Thanks! Your request is in. We’ll reach out soon.'}else if(response.status===503){message.textContent='Your email app will open with the details ready to send.';fallbackMailto(data)}else{throw new Error(result.error||'Unable to submit right now.')}}catch(error){message.textContent='The form could not send automatically. Your email app will open with your details ready to send.';fallbackMailto(data)}finally{button.disabled=false;button.innerHTML='Request a conversation <span aria-hidden="true">↗</span>'}});
})();